baseURL: https://eternity.bora.sh # todo: change site url.
title: Titolo del sito # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: logo2.jpeg # todo: add your custom logo to static/
  subtitle: Eternity is a minimalist Hugo theme designed for portfolio sites with a fresh feel. # todo: change default subtitle for your website.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Lovely Author # todo: set your full name.
  dontShowSource: true # please, do not do this :)
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    # todo: change these links.
    - icon: 'fab fa-github fa-lg'
      url: '/about/'
      landing: true

    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:eternity@bora.sh'
      landing: true

    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.bora.sh/eternity'
    # - icon: 'fab fa-linkedin-in fa-lg'
    #   url: 'https://linkedin.bora.sh/in/eternity'
  homepage: "/" # homepage link, mostly same with menu.main[0]
  specialPages:

  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: true # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: moda
      url: /moda
      weight: 1
    - name: teatro
      url: /teatro
      weight: 2
    - name: illustrazioni
      url: /illustrazioni
      weight: 3
    - name: schizzi
      url: /schizzi
      weight: 4
    # - name: about
    #   url: /about/
    #   weight: 5
